services:
    v1.9.0:
      image: leaker/deno:1.9.0
      build: 1/1.9.0

    v1.9.1:
      image: leaker/deno:1.9.1
      build: 1/1.9.1

    v1.9.2:
      image: leaker/deno:1.9.2
      build: 1/1.9.2

    v1.10.1:
      image: leaker/deno:1.10.1
      build: 1/1.10.1

    v1.10.2:
      image: leaker/deno:1.10.2
      build: 1/1.10.2

    latest:
      extends: v1.10.2
      image: leaker/deno:latest