name: update

# daily job
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.makever.outputs.updated }}
      dockerpath: ${{ steps.makever.outputs.dockerpath }}
      tag: ${{ steps.makever.outputs.tag }}
    steps:
      - uses: actions/checkout@master

      - name: run update script
        id: makever
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Log in to Docker Hub
        if: success() && steps.makever.outputs.updated == '1'
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: success() && steps.makever.outputs.updated == '1'
        id: meta
        uses: docker/metadata-action@master
        with:
          images: leaker/deno
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ steps.makever.outputs.tag }}

      # - name: Build and push Docker image
      #   if: success() && steps.makever.outputs.updated == '1'
      #   uses: docker/build-push-action@master
      #   with:
      #     context: ${{ steps.makever.outputs.dockerpath }}
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: commit and push change
      #   if: success() && steps.makever.outputs.updated == '1'
      #   env:
      #     GITHUB_EMAIL: ${{ secrets.EMAIL }}
      #     GITHUB_LOGIN: ${{ secrets.LOGIN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.name "$GITHUB_LOGIN"
      #     git config --global user.email "$GITHUB_EMAIL"
      #     git add .
      #     git commit -m "Update from Github Action"
      #     git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git